### ISSUE TITLE
Error ReferenceError: requestData is not defined

### ISSUE THREAD

**Issue by thomaswiedmann** [bartve/disconnect#31]
I'm new to node and disconnect. I get a error Error: **ReferenceError: requestData is not defined here** 

`app.get('/callback', function(req, res){
    var oAuth = new Discogs(requestData).oauth();   <=== Error ReferenceError: requestData is not defined
    oAuth.getAccessToken(
        req.query.oauth_verifier, // Verification code sent back by Discogs
        function(err, accessData){
            // Persist "accessData" here for following OAuth calls 
            res.send('Received access token!');
        }
    );
});`

Need some help. Thanks!

**Comment by bartve** [comment]
Your `requestData` variable must contain the object returned by this step https://github.com/bartve/disconnect#1-get-a-request-token

**Comment by thomaswiedmann** [comment]
Thanks!

Is there any best practice to do so? For example using localStorage https://www.npmjs.com/package/node-persist or easy some gloable var.

**Comment by bartve** [comment]
It's up to you how to temporarily store `requestData`. You only need it for the following OAuth call, so I'd say something in-memory and cleanup after you've got your `accessData` object which you use for the following OAuth calls, so that should be stored in a database or filesystem for long(er) term use.

**Comment by thomaswiedmann** [comment]
Thanks! Work well. Now I will build my samples.
